name: Release

on:
  push:
    branches:
      - main

jobs:
  SayHello:
  if: ${{ contains(github.event.head_commit.message, '[set version]')
  runs-on: ubuntu-latest
  steps:
  
  - run: echo "Success"
