name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  UpdateVersionFile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update version file
      run: echo ${{ github.ref }} >> VERSION.txt

    - name: Commit version file
      uses: test-room-7/action-update-file@v1
      with:
        file-path: VERSION.txt
        branch: "development"
        commit-msg: "[set version ${{ github.ref }}]"
        github-token: ${{ secrets.GITHUB_TOKEN }}
          
  MergeIntoMain:
    needs: UpdateVersionFile
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --all
        git checkout main
        git pull origin development --allow-unrelated-histories
        git checkout development
        git pull origin main --allow-unrelated-histories
        git merge -X theirs main
