name: Release

on:
  push:
    tags:
      - '*'

jobs:
  UpdateVersionFile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Update version file
      run: echo ${GITHUB_REF/refs\/tags\//} > VERSION.txt

    - name: Commit version file
      uses: test-room-7/action-update-file@v1
      with:
        file-path: VERSION.txt
        branch: "development"
        commit-msg: "[set version ${{ github.ref }}]"
        github-token: ${{ secrets.GITHUB_TOKEN }}
          
  MergeIntoMain:
    needs: UpdateVersionFile
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - run: |
        git fetch --all
        git checkout development
        git checkout main
        git merge development -X theirs
        git push origin main

  CreateGithubRelease:
  
  - name: Create Release
    id: create_release
    uses: actions/create-release@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      tag_name: ${GITHUB_REF/refs\/tags\//}
      release_name: Release ${GITHUB_REF/refs\/tags\//}
      body: ${{ github.event.head_commit.message }}
      draft: false
      prerelease: false
